- ntpcheck/checker/peerstats.go
Fix nasty crash when peer is not resolvable + skip peers with no proper IPs
ran it on host with some bad peers (pool + ntpd 2.8), no crashes
> [ntpcheck] fix peerstats when DNS resolution fails

- ntpcheck/checker/chrony.go
- ntpcheck/checker/ntpd.go
- ntpcheck/checker/serverstats.go
- ntpcheck/checker/system.go
- ntpcheck/cmd/serverstats.go
- ntpcheck/cmd/stats.go
- protocol/control/client.go
Now we support server stats on ntpd just as well.
Ran the code on host with ntpd:
```
abulimov@u1804:~/go/src/github.com/facebookincubator/ntp/ntpcheck$ ./ntpcheck serverstats
{"ntp.server.packets_received":1966,"ntp.server.packets_dropped":24}
```
and chrony:
```
[root@chronyhost ~]# ./ntpchkng serverstats
{"ntp.server.packets_received":2875803805,"ntp.server.packets_dropped":0}
```
> [ntpcheck] support serverstats with ntpd 4.2.8+

- ntpcheck/checker/runner.go
One-line fix to support ipv4 addresses
works with both v4 and v6 now:
```
abulimov@u1804:~/go/src/github.com/facebookincubator/ntp/ntpcheck$ ./ntpcheck stats -S 127.0.0.1:123
{"ntp.peer.delay":41.308,"ntp.peer.poll":128,"ntp.peer.jitter":4.277,"ntp.peer.offset":-1.187,"ntp.peer.stratum":2,"ntp.sys.frequency":13.911,"ntp.stat.error":false}
abulimov@u1804:~/go/src/github.com/facebookincubator/ntp/ntpcheck$ ./ntpcheck stats -S '[::1]:123'
{"ntp.peer.delay":41.308,"ntp.peer.poll":128,"ntp.peer.jitter":4.277,"ntp.peer.offset":-1.187,"ntp.peer.stratum":2,"ntp.sys.frequency":13.911,"ntp.stat.error":false}
```
> Make ntpcheck work over ipv4 (fixes #25)

- responder/server/server.go
* Improve messages to make it easier to distinguish from where a fatal is coming from
* Replace `fatal` with `error` when it fails to read a packet so that it can continue running
> improve fatal messages

- README.md
- ntpcheck/cmd/utils.go
- protocol/ntp/ntp_test.go
- protocol/ntp/ntp_test_darwin.go
- protocol/ntp/ntp_test_freebsd.go
- protocol/ntp/ntp_test_linux.go
- protocol/ntp/packet.go
- protocol/ntp/packet_darwin.go
- protocol/ntp/packet_freebsd.go
- protocol/ntp/packet_linux.go
- responder/server/server.go
Let's not confuse people and remove hardware timestamp reference for now
```
$ sudo go run github.com/facebookincubator/ntp/responder --ip 1.2.3.4 --ip 2.3.4.5 -interface lo0
WARN[0000] Creating 800 goroutine workers
WARN[0000] Starting 2 listener(s)
INFO[0000] Starting listener on 1.2.3.4:123
INFO[0000] Starting listener on 2.3.4.5:123
INFO[0000] Adding 2.3.4.5 to lo0
INFO[0000] Adding 1.2.3.4 to lo0
WARN[0013] Graceful shutdown
INFO[0013] Deleting 1.2.3.4 to lo0
INFO[0013] Deleting 2.3.4.5 to lo0
```
> Remove hardware timestamps reference

- responder/server/server.go
Since we set default logging level as "Info" we no longer need "Warning" hack. Additionally no more invalid query data is polluting the logs.
```
$ sudo go run github.com/facebookincubator/ntp/responder --ip 1.2.3.4 --ip 2.3.4.5 -interface lo0
WARN[0000] Creating 800 goroutine workers
WARN[0000] Starting 2 listener(s)
INFO[0000] Starting listener on 1.2.3.4:123
INFO[0000] Starting listener on 2.3.4.5:123
INFO[0000] Adding 1.2.3.4 to lo0
INFO[0000] Adding 2.3.4.5 to lo0
INFO[0020] Invalid query, discarding: &{115 102 115 100 1717832192 0 0 0 0 0 0 0 0 0 0}
^CWARN[0024] Graceful shutdown
INFO[0024] Deleting 1.2.3.4 to lo0
INFO[0024] Deleting 2.3.4.5 to lo0
```
```
$ sudo go run github.com/facebookincubator/ntp/responder --ip 1.2.3.4 --ip 2.3.4.5 -interface lo0
INFO[0000] Creating 800 …
```
> Improve logging levels

- ntpcheck/checker/checkresult.go
- ntpcheck/checker/chrony.go
- ntpcheck/checker/stats.go
Example run:
```
{"ntp.peer.delay":0,"ntp.peer.poll":256,"ntp.peer.jitter":0,"ntp.peer.offset":-0.030286000765045173,"ntp.peer.stratum":2,"ntp.sys.frequency":1.6121444702148438,"ntp.stat.error":false,"ntp.correction":-0.000021913370801485144}
```
> expose correction metric

- protocol/ntpshm/ntpshm.go
- protocol/ntpshm/ntpshm_test.go
Implement reading of NTP Shared Memory Segment (SHM0).
We don't use it for now.
* Create a segment by phc2sys from PHC
```
sudo /usr/sbin/phc2sys -E ntpshm -s ens2f0 -O 37 -m -l 7
```
* Add print in the test run:
```
&{mode:1 count:20634 clockTimeStampSec:1615474428 clockTimeStampUSec:668960 receiveTimeStampSec:1615474354 receiveTimeStampUSec:670570 leap:0 precision:-30 nsamples:0 valid:1 clockTimeStampNSec:668960937 receiveTimeStampNSec:670570630 dummy:[0 0 0 0 0 0 0 0]}
```
> Add ntpshm lib

- protocol/ntpshm/ntpshm.go
On the user side it's much nicer to call ntpshm.Time() than ntpshm.SHMTime()
> Rename SHMTime() to Time()

- README.md
- leapsectz/leapsectz.go
- leapsectz/leapsectz_test.go
- ntpcheck/cmd/utils.go
Chrony has a `leapsectz` directive to get the next leap second info from the system tz database.
I am adding a `leapsectz` package to get visibility of the information in there.
Example run:
```
ntpchkng utils printleap
1972-07-01 00:00:00 +0000 UTC
1973-01-01 00:00:00 +0000 UTC
1974-01-01 00:00:00 +0000 UTC
1975-01-01 00:00:00 +0000 UTC
1976-01-01 00:00:00 +0000 UTC
1977-01-01 00:00:00 +0000 UTC
1978-01-01 00:00:00 +0000 UTC
1979-01-01 00:00:00 +0000 UTC
1980-01-01 00:00:00 +0000 UTC
1981-07-01 00:00:00 +0000 UTC
1982-07-01 00:00:00 +0000 UTC
1983-07-01 00:00:00 +0000 UTC
1985-07-01 00:00:00 +0000 UTC
1988-01-01 00:00:00 +0000 UTC
1990-01-01 00:00:00 +0000 UTC
1991-01-01 00:00:00 +0000 UTC
1992-07-01 00:00:00 +0000 UTC
1993-07-01 00:00:00 +0000 UTC
1994-07-01 00:00:00 +0000 UTC …
```
> leapsectz package

- leapsectz/leapsectz.go
Before:
```
golangci-lint run --enable deadcode --enable varcheck --enable staticcheck
leapsectz.go:59:11: Error return value of `r.Read` is not checked (errcheck)
if r.Read(magic); string(magic) != "TZif" {
```
After:
```
golangci-lint run --enable deadcode --enable varcheck --enable staticcheck
echo $?
0
```
> [leapsectz] lint

- responder/main.go
- responder/server/interfaces.go
- responder/server/server.go
- responder/stats/json.go
Remove the `SetPrefix` and `Report` methods.
Encourage stats pulling instead of pushing.
> [responder] remove SetPrefix and Report methods

- responder/main.go
- responder/stats/json.go
- responder/stats/json_test.go
Remove the prefix. Let the collector set one if it is needed.
> [responder] remove prefix

- protocol/ntpshm/ntpshm.go
- protocol/ntpshm/ntpshm_test.go
This diff:
* Changes the way we read structure from the pointer. No more reflect
* Update test data from `gpsd` output in `shm`, not `phc2sys`
* Fixes unit test for 32 bit architecture
```
$ env GOOS=linux GOARCH=386 go test ./...
ok  	github.com/facebookincubator/ntp/protocol/ntpshm	0.003s
$ env GOOS=linux GOARCH=amd64 go test ./...
ok  	github.com/facebookincubator/ntp/protocol/ntpshm	0.005s
```
Parsing still works correctly where used:
```
$ ./ptp4u -shm true
INFO[0000] UTC offset is: 37s
```
> Fix ntpshm for 386

- ntpcheck/checker/chrony.go
- ntpcheck/checker/serverstats.go
- protocol/chrony/client.go
- protocol/chrony/packet.go
Server stats response type and struct changed in: https://github.com/mlichvar/chrony/commit/ab54f76a38a27410ba168ea739f4575c65d4acf4
Add support for both response types.
Before:
```
ntpchkng stats
FATA[0000] failed to get 'serverstats' response: not implemented reply type 22 from &{Version:6 PKTType:2 Res1:0 Res2:0 Command:54 Reply:22 Status:0 Pad1:0 Pad2:0 Pad3:0 Sequence:3 Pad4:0 Pad5:0} 
```
After:
```
ntpchkng stats
{"ntp.peer.delay":13.619720935821533,"ntp.peer.poll":64,"ntp.peer.jitter":0.00044080343286623247,"ntp.peer.offset":0.05689799945685081,"ntp.peer.stratum":2,"ntp.sys.frequency":-13.564138412475586,"ntp.stat.error":false,"ntp.correction":9.899275843494593e-10}
```
> [ntpcheck] support serverstats with chrony 4.1

- ntpcheck/checker/checkresult.go
- ntpcheck/checker/chrony.go
- ntpcheck/checker/chrony_test.go
- ntpcheck/checker/ntpd.go
- ntpcheck/checker/ntpd_test.go
- ntpcheck/checker/runner.go
- ntpcheck/cmd/serverstats.go
* Remove logic to automatically choose between UDP or unix socket connection for Chrony
* Decouple ServerStats from the main Check function
* Use unix socket only for the ServerStats
* Use UDP for everything else
> [ntpcheck] decouple serverstats

- ntpcheck/checker/checkresult.go
- ntpcheck/checker/chrony.go
- ntpcheck/checker/chrony_test.go
- ntpcheck/checker/runner.go
- protocol/chrony/client.go
- protocol/chrony/client_test.go
- protocol/chrony/helpers.go
* Remove the `Incomplete` field from the `NTPCheckResult`struct
* Remove the fallback logic to have more control of what data is going to be gathered
* Add `RunNTPData` to explicitly use the unix socket and private protocol
> [ntpcheck] decouple ntpdata

- protocol/chrony/client.go
- protocol/chrony/packet.go
> Thanks for submitting a pull request! We appreciate you spending the time to work on these changes. Please provide enough information so that others can review your pull request. The three fields below are mandatory.
There are only two fields, but ;)
> Explain the **motivation** for making this change. What existing problem does the pull request solve?
Chrony puts some source information into the "SourceData" reply, which the library already handles, and some additional information into the "SourceStats" reply, which this PR adds.  I needed the stats to keep track of how far off 1Hz various PPS sources are (the "ResidFreqPPM" element).
> Demonstrate the code is solid. Example: The exact commands you ran and their output, copy text from console etc.
I was hoping there would be some test …
> protocol/chrony: support 'sourcestats' query

- ntpcheck/cmd/diag.go
Exposing pre existing correction field to diag results
Warning Threshold: 1 minute
Error Threshold: 10 minutes
`./ntp/ntpcheck/ntpcheck/ntpcheck/ntpcheck diag`
NOTE: I ran 3 times and manually adjusted correction to get different cases
```
[ OK ] Leap indicator is set to 'none'
[ OK ] Sys Peer offset is 0.007ms, we expect it to be within 1.0ms
[ OK ] Sys Peer jitter is 0.000ms, we expect it to be within 1.0ms
[ OK ] Current correction is 0.003ms, we expect it to be within 60000.0ms
[ OK ] All 18 peers are OK (have 'flash' indicator set to 0)
[ OK ] All 18 peers were reachable 8/8 last sync attempts
```
```
[ OK ] Leap indicator is set to 'none'
[ OK ] Sys Peer offset is 0.007ms, we expect it to be within 1.0ms
[ OK ] Sys Peer jitter is 0.000ms, we expect it to be within 1.0ms
[WARN] …
```
> Adding check correction metric to ntpcheck diag

- .gitignore
- README.md
Updated `README.md` and `.gitignore` with the following features:
- Add project status badges to `READE.md`
- Refactor `README.md` format
- Add tests output files to `.gitignore`
> Add project status badges to README and updated gitignore

- calnex/api/api.go
- calnex/api/api_test.go
- calnex/cmd/cert.go
Implement a basic certificate update function.
API is designed to accept `[]byte`.
Open source implementation takes cert from the file. Private implementations can take it straight from APIs.
```
$ openssl s_client -connect calnex01.example.com:443 2>/dev/null | openssl x509 -noout -dates
notAfter=Aug 14 13:06:09 2022 GMT
```
```
$ ./calnex -- cert --target calnex01.example.com --file /tmp/calnex.pem --apply
```
```
$ openssl s_client -connect calnex01.example.com:443 2>/dev/null | openssl x509 -noout -dates
notAfter=Sep 12 15:08:38 2022 GMT
```
> [calnex] implement cert subcommand

- calnex/cmd/clear.go
- calnex/cmd/firmware.go
- calnex/cmd/reboot.go
- calnex/config/config.go
- calnex/export/export.go
- calnex/firmware/firmware.go
* Add apply to `clear` and `reboot` commands
* Fix comments after deprecating protocol
```
$ calnex reboot --target calnex03.lla1.fbinfra.net
INFO[0000] dry run. Exiting
```
```
$ calnex clear --target calnex03.lla1.fbinfra.net
INFO[0000] dry run. Exiting
```
> [calnex] add apply to dangerous commands

- calnex/api/api.go
- calnex/api/api_test.go
- calnex/export/export.go
- calnex/export/export_test.go
Let's not rely on DNS.
Unittests
```
$ calnex export --source calnex03.example.com
...
{"float":{"value":-0.0000138495},"int":{"time":1643368864},"normal":{"channel":"2","target":"1.2.3.4","protocol":"ntp","source":"calnex03.example.com"}}
```
> [Calnex] eliminate DNS dependency

- cmd/ptpcheck/cmd/servicestats.go
- ptp/protocol/management.go
- ptp/protocol/management_tlvs.go
- ptp/protocol/ptp4l.go
- ptp/protocol/ptp4l_test.go
We recently [contributed PORT_SERVICE_STATS_NP management TLV to linuxptp](https://github.com/richardcochran/linuxptp/commit/cfbb8bdb50f5a38687fcddccbe6a264c6a078bbd),
which allows to open-source related code.
Also, added unittest and fixed marshalling for PortStatsNP along the way.
unittests
```
> ptpcheck servicestats | jq .
{
"ptp.servicestats.announce_timeout": 1,
"ptp.servicestats.sync_timeout": 0,
"ptp.servicestats.delay_timeout": 0,
"ptp.servicestats.unicast_service_timeout": 0,
"ptp.servicestats.unicast_request_timeout": 0,
"ptp.servicestats.master_announce_timeout": 2809,
"ptp.servicestats.master_sync_timeout": 5616,
"ptp.servicestats.qualification_timeout": 0,
"ptp.servicestats.sync_mismatch": 0,
"ptp.servicestats.followup_mismatch": 0
}
```
> Added PTP PORT_SERVICE_STATS_NP TLV and ptpcheck subcommand

- calnex/cmd/cmd.go
- cmd/ntpcheck/checker/chrony.go
- cmd/ntpcheck/checker/runner.go
- cmd/ntpcheck/checker/system.go
- leapsectz/leapsectz.go
- ntp/chrony/packet.go
- ntp/protocol/ntp.go
- ntp/shm/ntpshm.go
- ptp/protocol/protocol.go
- ptp/protocol/unicast.go
- ptp/ptp4u/server/server.go
- ptp/ptp4u/server/server_test.go
- ptp/ptp4u/server/subscription.go
- ptp/ptp4u/server/worker.go
- ptp/ptp4u/server/worker_test.go
- timestamp/timestamp.go
It used to be:
```
go run golang.org/x/lint/golint ./...
calnex/cmd/cmd.go:24:5: exported var RootCmd should have comment or be unexported
cmd/ntpcheck/checker/chrony.go:38:32: exported func DialUnix returns unexported type *checker.chronyConn, which can be annoying to use
cmd/ntpcheck/checker/system.go:62:1: exported function NewSystemVariablesFromChrony should have comment or be unexported
leapsectz/leapsectz.go:19:1: package comment is detached; there should be no blank lines between it and the package statement
ntp/chrony/packet.go:450:6: exported type SourceStats should have comment or be unexported
ntp/protocol/ntp.go:17:1: package comment should be of the form "Package protocol ..."
ntp/shm/ntpshm.go:35:7: don't use ALL_CAPS in Go names; use CamelCase
ntp/shm/ntpshm.go:40:1: …
```
> Make golint happy

- cmd/ptp4u/main.go
- ptp/ptp4u/server/config.go
- ptp/ptp4u/server/config_test.go
- ptp/ptp4u/server/server.go
Option to use leapsectz lib
```
$ /usr/local/bin/ptp4u -workers 200 -timestamptype hardware -loglevel error -leapsectz
```
> [ptp4u] use leapsectz lib to determine leapsecond

- ptp/ptp4u/server/server.go
If we want to respond to DelayRequests back to ephemeral port (which is against the standard, but there are reasons), we need to update the subscription accordingly.
tests pass, local testing shows it works
> [ptp4u] update gclisa on renewal

- calnex/cert/cert.go
- calnex/cert/cert_test.go
- calnex/cmd/cert.go
Add a "cert" package which will do some validation of the supplied PEM
file for the "calnex cert" command.
Validates:
* The PEM file parses
* We have a private key
* We have a cert
* One of the cert CNs matches the supplied hostname
* The cert validity date before and ends after the supplied time.
This change provides a basic level of validation of any new certificate being uploaded to the Calnex to try and prevent common errors that might result in unavailability of the remote API.
```
$ go test ./...
ok  	github.com/facebook/time/calnex/api	0.080s
ok  	github.com/facebook/time/calnex/cert	0.007s
ok  	github.com/facebook/time/calnex/cmd	0.006s
ok  	github.com/facebook/time/calnex/config	0.016s
ok  	github.com/facebook/time/calnex/export	0.014s
ok …
```
> [calnex] Add certificate checking for cert command

- cmd/ntpcheck/cmd/utils.go
Add debug logging to the ntpcheck utils ntpdate to print all 4 timestamps
```
$ go run github.com/facebook/time/cmd/ntpcheck utils ntpdate -s time1.facebook.com -v
Server: time1.facebook.com:123, Requests: 3
DEBU[0000] Client TX timestamp: 2022-02-05 00:39:14.769815 +0000 GMT m=+0.045096321, Origin TX timestamp: 2022-02-05 00:39:14.769814999 +0000 GMT
DEBU[0000] Server RX timestamp: 2022-02-05 00:39:14.85949871 +0000 GMT
DEBU[0000] Server TX timestamp: 2022-02-05 00:39:14.859621254 +0000 GMT
DEBU[0000] Client RX timestamp: 2022-02-05 00:39:14.795314 +0000 GMT
DEBU[0000] Client TX timestamp: 2022-02-05 00:39:14.79637 +0000 GMT m=+0.071651730, Origin TX timestamp: 2022-02-05 00:39:14.796369999 +0000 GMT
DEBU[0000] Server RX timestamp: 2022-02-05 00:39:14.883073097 +0000 GMT
DEBU[0000] …
```
> [ntpdate] verbose logging

- ntp/responder/server/server.go
Reusing the `request` leads to data race
internal testing
> [ntp/reponser] fix reusing request

- cmd/ntpcheck/cmd/utils.go
Per standard, we need to use Origin timestamp returned by the server for the calculation.
Also, log error if origin timestamp is not equal to what we sent as Transmit timestamp (one of the basic sanity checks prescribed by the standard).
```
> ./ntpcheck utils ntpdate -s time.facebook.com
Server: time.facebook.com:123, Requests: 3
Last:
Stratum: 1, Current time: 2022-02-11 04:15:23.8979715 -0800 PST
Offset: 0.018336s (18.336179ms), Network delay: 0.164745s (164.745060ms)
Average:
Offset: 0.018281s (18.281252ms), Network delay: 0.164744s (164.743510ms)
```
> [cmd/ntpcheck] ntpdate: fix delay calculation, sanity check

- ptp/protocol/management_tlvs.go
- ptp/protocol/ptp4l.go
- ptp/protocol/ptp4l_test.go
- ptp/protocol/types.go
- ptp/protocol/types_test.go
Add more useful stuff:
* PORT_PROPERTIES_NP management TLV (ptp4l-specific), with management client helper
* PortState enum
* TransportType enum
* PortAddress struct with marshalling/unmarhalling
* Timestamping enum (ptp4l-specific)
unittests
> [ptp/protocol] add more types and PORT_PROPERTIES_NP TLV

- cmd/ptpcheck/cmd/sources.go
- go.sum
- ptp/protocol/management_tlvs.go
- ptp/protocol/ptp4l.go
- ptp/protocol/ptp4l_test.go
New UNICAST_MASTER_TABLE_NP management TLV was just [merged to linuxptp](https://github.com/richardcochran/linuxptp/commit/c63d1fca3f47ea22eae076114ce263bc4f30725a), this PR adds Go protocol support for it.
And of course the `ptpcheck sources` subcommand that uses this new TLV.
unittests
```
> ./ptpcheck sources
+----------+----------------------+----------------------------------+-----------+--------+----------+---------+------------+-----------+--------------+
| SELECTED |       IDENTITY       |       ADDRESS      |   STATE   | CLOCK  | VARIANCE |  P1:P2  | OFFSET(NS) | DELAY(NS) |  LAST SYNC   |
+----------+----------------------+--------------------+-----------+--------+----------+---------+------------+-----------+--------------+
| false    | b8cef6.fffe.7349d4-1 | time01.example.com …
```
> [ptp] add UNICAST_MASTER_TABLE_NP and ptpcheck sources

- cmd/ptpcheck/cmd/oscillatord.go
- oscillatord/monitoring.go
- oscillatord/monitoring_test.go
Expose read `satellites_count` from oscillatord socket and expose it via `ptpcheck oscillatord`
```
./ptpcheck_oleg oscillatord
Oscillator:
model: mRO50
fine_ctrl: 2761
coarse_ctrl: 4186407
lock: true
temperature: 32.51C
GNSS:
fix: 3D (5)
fixOk: true
antenna_power: ON (1)
antenna_status: OPEN (4)
leap_second_change: NO WARNING (0)
leap_seconds: 18
satellites_count: 9
```
> [ptpcheck] display satellites_count in oscillatord output

- calnex/api/api.go
- calnex/api/api_test.go
- calnex/config/config.go
- calnex/config/config_test.go
- calnex/export/export.go
- calnex/export/export_test.go
- calnex/firmware/firmware_test.go
Some fixes coming with the new FW release:
* 32 channels
* Bools are longer strings in json
* `server_ip` added to clock channels
* Using `installed` to determine if channel is physically installed even if it's set to used
* Stop measurement before rebooting
> [calnex] new API improvements

- ptp/ptp4u/server/server.go
downgrade level of "subscription expired or did not handle well on client side" log message.
> [ptp4u] downgrade to info

- calnex/api/api.go
- calnex/api/api_test.go
PPS export is done via `datatype=te` not datatype=tie
```
$ curl "https://calnex01.example.com/api/getdata?channel=c&datatype=te"
1647612864.021067,-1729.652058119275
1647612864.930176,-1729.561166749330
1647612865.839285,-1729.470275380428
```
> [calnex] change PPS export datatype

- cmd/ptp4u/main.go
- ptp/ptp4u/server/config.go
- ptp/ptp4u/server/subscription.go
- ptp/ptp4u/server/subscription_test.go
Introduce 2 new configuration options ClockClass and ClockAccuracy.
Use these 2 values in announce packet instead of hardcode values.
Run server
Tcpdump announce message
Look inside with wireshark
Values are set to "defaults"
Also unit tests!
> [ptp4u] make clockAccuracy and clockClass configurable

- cmd/ptp4u/main.go
- cmd/ptp4u/testdata/ptp4u.yaml
- go.mod
- go.sum
- ptp/ptp4u/server/config.go
- ptp/ptp4u/server/config_test.go
- ptp/ptp4u/server/server_test.go
- ptp/ptp4u/server/subscription.go
- ptp/ptp4u/server/subscription_test.go
- ptp/ptp4u/server/worker_test.go
* Split "config" struct in 2 parts:
* Static - things which never change during lifetime aka IP or iface
* Dynamic - thing that can be updated without service restart
* Allow `flags` (cmd line arguments) to configure *only* static section
* Introduce support of yaml configs *only* for dynamic section of the config
This way we are confident that entire config will be "reload" vs just part of the settings.
Deploy new binary to a test host. See UTC offset for example working.
Nothing changes as provided defaults match previous behaviour:
Print options:
```
$ ./ptp4u
&{StaticConfig:{ConfigFile: DebugAddr: DSCP:0 Interface:eth0 IP::: Leapsectz:false LogLevel:warning MonitoringPort:8888 QueueSize:0 RecvWorkers:10 SendWorkers:100 SHM:false TimestampType:hardware} DynamicConfig:{ClockAccuracy:33 …
```
> [ptp4u] introduce the yaml config file support

- ptp/ptp4u/server/config.go
- ptp/ptp4u/server/config_test.go
- ptp/ptp4u/server/server.go
- ptp/ptp4u/server/server_test.go
- ptp/ptp4u/stats/json.go
- ptp/ptp4u/stats/json_test.go
- ptp/ptp4u/stats/stats.go
- ptp/ptp4u/stats/stats_test.go
Reload dynamic portion of the config on SIGHUP
Take a default config:
```
$ cat /etc/ptp4u.yaml
clockaccuracy: 0x21
clockclass: 6
draininterval : "30s"
maxsubduration: "1h"
metricinterval : "1m"
minsubinterval: "1s"
utcoffset     : "37s"
```
Run ptp4u with config option specified:
```
/usr/local/bin/ptp4u -config /etc/ptp4u.yaml
```
See all good.
Change utcoffset to 38s:
```
$ cat /etc/ptp4u.yaml
clockaccuracy: 0x21
clockclass: 6
draininterval : "30s"
maxsubduration: "1h"
metricinterval : "1m"
minsubinterval: "1s"
utcoffset     : "38s"
```
Send SIGHUP:
```
$ kill -1 563181
```
Profit:
> [ptp4u] reload config on SIGHUP

- cmd/c4u/main.go
- cmd/ptpcheck/cmd/oscillatord.go
- oscillatord/monitoring.go
- ptp/c4u/clock/clock.go
- ptp/c4u/clock/oscillatord.go
- ptp/c4u/clock/ts2phc.go
- ptp/c4u/utcoffset/utcoffset.go
- ptp/c4u/utcoffset/utcoffset_test.go
- ptp/protocol/ptp4l.go
- ptp/protocol/types.go
- ptp/ptp4u/server/config.go
- ptp/ptp4u/server/subscription_test.go
Create a new cli tool (initial version) which can override the ptp4u config generated from different sources:
* UTC offset from leapsectz
* ClockQuality from oscillatord and ts2phc
```
$ ./c4u_oleg
INFO[0000] Current: &{ClockAccuracy:254 ClockClass:7 DrainInterval:30s MaxSubDuration:1h0m0s MetricInterval:1m0s MinSubInterval:1s UTCOffset:1m40s}
INFO[0000] Pending: &{ClockAccuracy:33 ClockClass:6 DrainInterval:30s MaxSubDuration:1h0m0s MetricInterval:1m0s MinSubInterval:1s UTCOffset:37s}
```
```
$ ./c4u_oleg -save
```
```
cat /etc/ptp4u.yaml
clockaccuracy: 33
clockclass: 6
draininterval: 30s
maxsubduration: 1h0m0s
metricinterval: 1m0s
minsubinterval: 1s
utcoffset: 37s
```
> [c4u] initial version

- cmd/ptp4u/main.go
- ptp/ptp4u/server/server.go
- ptp/ptp4u/server/server_test.go
* Move logic inside of the server package (next to already implemented SIGHUP logic)
* Simplify main
* Add unit test
```
$ cat /var/run/ptp4u.pid
2554230
$ kill -1 2554230
<reload works>
$ systemctl stop ptp4u
$ cat /var/run/ptp4u.pid
cat: /var/run/ptp4u.pid: No such file or directory
```
> [ptp4u] move signal handling logic to server

- cmd/c4u/main.go
- cmd/ptp4u/main.go
- ptp/c4u/c4u.go
- ptp/c4u/c4u_test.go
- ptp/c4u/clock/clock.go
- ptp/c4u/clock/clock_test.go
- ptp/c4u/clock/oscillatord.go
- ptp/c4u/clock/ts2phc.go
- ptp/protocol/types.go
- ptp/protocol/types_test.go
- ptp/ptp4u/server/config.go
- ptp/ptp4u/server/config_test.go
- ptp/ptp4u/server/server.go
- ptp/ptp4u/server/server_test.go
* Implement a TAU support in c4u. We will now observe last N (default is 60) values and generate config based on worst data during this window. Data is collected once a second.
* Duration to ptp.ClockAccuracy conversion
* More unit tests
```
./c4u_oleg
INFO[0000] Current: &{ClockAccuracy:33 ClockClass:7 DrainInterval:30s MaxSubDuration:1h0m0s MetricInterval:1m0s MinSubInterval:1s UTCOffset:37s}
INFO[0000] Pending: &{ClockAccuracy:33 ClockClass:6 DrainInterval:30s MaxSubDuration:1h0m0s MetricInterval:1m0s MinSubInterval:1s UTCOffset:37s}
INFO[0001] Current: &{ClockAccuracy:33 ClockClass:7 DrainInterval:30s MaxSubDuration:1h0m0s MetricInterval:1m0s MinSubInterval:1s UTCOffset:37s}
INFO[0001] Pending: &{ClockAccuracy:33 ClockClass:6 DrainInterval:30s MaxSubDuration:1h0m0s MetricInterval:1m0s …
```
> [c4u] implement sliding monitoring window (TAU)

- leapsectz/leapsectz.go
- leapsectz/leapsectz_test.go
- ptp/c4u/utcoffset/utcoffset.go
Leap second file `/usr/share/zoneinfo/right/UTC` is coming with `tzdata` and distributed in advance.
If leap second is added it will be added in advance.
This diff adds a check inside the `Latest()` so we don't return a leap second which will only happen in couple of months.
> [leapsec] exclude 'future' leap seconds from Latest() list

- cmd/c4u/main.go
- go.mod
- go.sum
- ptp/c4u/c4u.go
- ptp/c4u/c4u_test.go
- ptp/c4u/clock/clock.go
- ptp/c4u/clock/clock_test.go
- ptp/c4u/clock/math.go
- ptp/c4u/clock/math_test.go
- ptp/c4u/clock/oscillatord.go
- ptp/c4u/clock/oscillatord_test.go
- ptp/c4u/clock/ts2phc.go
We want to smooth out/filter the spikes in the phc offsets. This change introduces configurable math for clock accuracy calculation based on phc offset.
unittests, local runs
> [c4u] better math for clockAccuracy

- cmd/ptpcheck/cmd/oscillatord.go
- oscillatord/monitoring.go
- oscillatord/monitoring_test.go
```
$ ./ptpcheck oscillatord
Oscillator:
model: mRO50
fine_ctrl: 0
coarse_ctrl: 0
lock: false
temperature: 32.00C
GNSS:
fix: 3D (5)
fixOk: true
antenna_power: ON (1)
antenna_status: OPEN (4)
leap_second_change: NO WARNING (0)
leap_seconds: 18
satellites_count: 23
Clock:
class: Holdover (7)
offset: 5450
```
```
$ ./ptpcheck_oleg oscillatord --json
{"ptp.timecard.temperature":31,"ptp.timecard.lock":0,"ptp.timecard.gnss.fix_num":5,"ptp.timecard.gnss.fix_ok":1,"ptp.timecard.gnss.antenna_power":1,"ptp.timecard.gnss.antenna_status":4,"ptp.timecard.gnss.leap_second_change":0,"ptp.timecard.gnss.leap_seconds":18,"ptp.timecard.gnss.satellites_count":24,"ptp.timecard.clock.class":7,"ptp.timecard.clock.offset":6655}
```
> [oscillatord] process clock data

- oscillatord/monitoring.go
- oscillatord/monitoring_test.go
- ptp/c4u/clock/clock.go
- ptp/c4u/clock/clock_test.go
- ptp/c4u/clock/oscillatord.go
- ptp/c4u/clock/oscillatord_test.go
* c4u now reads actual output of oscillatord (class and offset)
* oscillatord offset is a proper time.Duration vs int before
* More unit tests
```
$ ptpcheck oscillatord
...
Clock:
class: Lock (6)
offset: -7
```
```
$ ./c4u
INFO[0000] Current: &{ClockAccuracy:34 ClockClass:6 DrainInterval:30s MaxSubDuration:1h0m0s MetricInterval:1m0s MinSubInterval:1s UTCOffset:37s}
INFO[0000] Pending: &{ClockAccuracy:32 ClockClass:6 DrainInterval:30s MaxSubDuration:1h0m0s MetricInterval:1m0s MinSubInterval:1s UTCOffset:37s}
```
```
$ cat /etc/ptp4u.yaml
clockaccuracy: 32
clockclass: 6
```
> [c4u] use oscillatord output

- cmd/ptpcheck/cmd/oscillatord.go
- oscillatord/monitoring.go
- oscillatord/monitoring_test.go
* Move conversion logic to a struct
* Cover with tests
* Export `fine_ctrl` and `coarse_ctrl`
Unittests 
Ptpcheck works
```
./ptpcheck oscillatord --json
{"ptp.timecard.oscillator.temperature":44,"ptp.timecard.oscillator.fine_ctrl":-18924,"ptp.timecard.oscillator.coarse_ctrl":500,"ptp.timecard.oscillator.lock":1,"ptp.timecard.gnss.fix_num":5,"ptp.timecard.gnss.fix_ok":1,"ptp.timecard.gnss.antenna_power":0,"ptp.timecard.gnss.antenna_status":3,"ptp.timecard.gnss.leap_second_change":0,"ptp.timecard.gnss.leap_seconds":18,"ptp.timecard.gnss.satellites_count":25,"ptp.timecard.clock.class":6,"ptp.timecard.clock.offset":0}
```
> [oscillatord] move/extend/test json convertion logic

- cmd/c4u/main.go
- ptp/c4u/c4u.go
- ptp/c4u/c4u_test.go
- ptp/c4u/stats/json.go
- ptp/c4u/stats/json_test.go
- ptp/c4u/stats/stats.go
- ptp/c4u/stats/stats_test.go
Export runtime stats, similar to other services.
unittests
local run
```
> curl 127.0.0.1:8889; echo;
{"clockaccuracy":254,"clockclass":52,"dataerror":5,"oscillatoroffset":0,"phcoffset":0,"reload":0,"utcoffset":37}
```
> [c4u] export stats

- ptp/c4u/c4u.go
- ptp/c4u/stats/json.go
- ptp/c4u/stats/json_test.go
- ptp/c4u/stats/stats.go
- ptp/c4u/stats/stats_test.go
- ptp/ptp4u/server/server.go
- ptp/ptp4u/stats/json.go
- ptp/ptp4u/stats/json_test.go
- ptp/ptp4u/stats/stats.go
- ptp/ptp4u/stats/stats_test.go
Best practice is including published stat unit in the name.
tests passs
run c4u
```
> curl 127.0.0.1:8889; echo;
{"clockaccuracy":254,"clockclass":52,"dataerror":13,"oscillatoroffset_ns":0,"phcoffset_ns":0,"reload":0,"utcoffset_sec":37}
```
> [ptp] update stat names to include units

- ptp/c4u/clock/clock.go
- ptp/c4u/clock/clock_test.go
- ptp/protocol/types.go
- ptp/protocol/types_test.go
* In holdover we don't know the offset. Let's fallback to 1us or worse
* In uncalibrated state we don't know the offset - let's say it
```
$ cat /etc/ptp4u.yaml
clockaccuracy: 35
clockclass: 7
```
> [c4u] override clockAccuracy while in holdover and uncalibrated classes

- cmd/c4u/main.go
- ptp/c4u/c4u.go
- ptp/c4u/c4u_test.go
- ptp/c4u/clock/clock.go
- ptp/c4u/clock/clock_test.go
Periodically we get a very good clockAccuracy based on offsets (<100ns or even <25ns). Very often it doesn't really matter but it causes regeneration of the ptp4u config and subsequent client migration/rebalancing.
This option allows us to set baselines which are "best case scenario" and we will never go lower in accuracy.
```
Current: &{ClockAccuracy:33 ClockClass:13 DrainInterval:30s MaxSubDuration:1h0m0s MetricInterval:1m0s MinSubInterval:1s UTCOffset:37s}
Pending: &{ClockAccuracy:34 ClockClass:13 DrainInterval:30s MaxSubDuration:1h0m0s MetricInterval:1m0s MinSubInterval:1s UTCOffset:37s}
```
> [c4u] implement baseline support

- calnex/api/api.go
Reset = false means don't reset the last read position data.
While having Reset = true is useful to ensure we always export all the data, it's getting slower and slower especially with PPS (86400) measurements X several channels.
```
$ calnex export --source calnex01.example.com --channel d
{"float":{"value":-3.2908e-8},"int":{"time":1652464950},"normal":{"channel":"d","target":"1.2.3.4","protocol":"pps","source":"calnex01.example.com"}}
{"float":{"value":-3.5782e-8},"int":{"time":1652464951},"normal":{"channel":"d","target":"1.2.3.4","protocol":"pps","source":"calnex01.example.com"}}
```
```
$ calnex export --source calnex01.example.com --channel d
{"float":{"value":-3.4283e-8},"int":{"time":1652464952},"normal":{"channel":"d","target":"1.2.3.4","protocol":"pps","source":"calnex01.example …
```
> [calnex] set reset=false in getdata call

- ptp/c4u/clock/oscillatord.go
- ptp/c4u/clock/oscillatord_test.go
We may be losing "lock" in a long holdover. We shouldn't switch to uncalibrated state and keep holdovering.
To check for empty struct its enough to just check the class > 0 
```
INFO[0001] Current: &{ClockAccuracy:254 ClockClass:52 DrainInterval:30s MaxSubDuration:1h0m0s MetricInterval:1m0s MinSubInterval:1s UTCOffset:37s}
INFO[0001] Pending: &{ClockAccuracy:35 ClockClass:7 DrainInterval:30s MaxSubDuration:1h0m0s MetricInterval:1m0s MinSubInterval:1s UTCOffset:37s}
```
> [c4u] check clock class > 0

- ptp/protocol/types.go
- ptp/protocol/types_test.go
Just a helper function to get MAC from ClockIdentity.
tests pass
> [ptp] add ClockIdentity to MAC function

- calnex/config/config.go
- calnex/config/config_test.go
Add a field to store the target name in the measurement config.
> [calnex] store target name

- oscillatord/monitoring.go
- oscillatord/monitoring_test.go
Latest oscillatord only accepts a valid json, no more `\n`
`ptpcheck` works
```
./ptpcheck oscillatord
Oscillator:
model: mRO50
fine_ctrl: 2105
coarse_ctrl: 4186391
lock: true
temperature: 36.29C
GNSS:
fix: 3D (5)
fixOk: true
antenna_power: ON (1)
antenna_status: OPEN (4)
leap_second_change: NO WARNING (0)
leap_seconds: 18
satellites_count: 27
Clock:
class: Calibrating (13)
offset: -25
```
`c4u` works:
```
Current: &{ClockAccuracy:254 ClockClass:52 DrainInterval:30s MaxSubDuration:1h0m0s MetricInterval:1m0s MinSubInterval:1s UTCOffset:37s}
Pending: &{ClockAccuracy:34 ClockClass:13 DrainInterval:30s MaxSubDuration:1h0m0s MetricInterval:1m0s MinSubInterval:1s UTCOffset:37s}
```
> [oscillatord] pass empty json to oscillatord

- oscillatord/monitoring.go
- oscillatord/monitoring_test.go
More granular data for oscillator temperature.
unittests
```
> ./ptpcheck oscillatord --json | jq .
{
"ptp.timecard.clock.class": 6,
"ptp.timecard.clock.offset": 11,
"ptp.timecard.gnss.antenna_power": 1,
"ptp.timecard.gnss.antenna_status": 4,
"ptp.timecard.gnss.fix_num": 5,
"ptp.timecard.gnss.fix_ok": 1,
"ptp.timecard.gnss.leap_second_change": 0,
"ptp.timecard.gnss.leap_seconds": 18,
"ptp.timecard.gnss.satellites_count": 28,
"ptp.timecard.oscillator.coarse_ctrl": 10000,
"ptp.timecard.oscillator.fine_ctrl": -750,
"ptp.timecard.oscillator.lock": 1,
"ptp.timecard.oscillator.temperature": 42.655
}
```
> [oscillatord] report temperature as float in monitoring JSON

- cmd/ptpcheck/cmd/oscillatord.go
- oscillatord/monitoring.go
- oscillatord/monitoring_test.go
Cover new monitoring values
1. Socket sends this json:
```
{ "Action requested": "None", "disciplining": { "status": "LOCK_HIGH_RESOLUTION", "current_phase_convergence_count": -1, "valid_phase_convergence_threshold": -1, "convergence_progress": 0.0, "tracking_only": "false", "ready_for_holdover": "false" }, "clock": { "class": "Lock", "offset": 2 }, "oscillator": { "model": "sa5x", "fine_ctrl": -625, "coarse_ctrl": 10000, "lock": true, "temperature": 46.935000000000002 }, "gnss": { "fix": 3, "fixOk": true, "antenna_power": 1, "antenna_status": 2, "lsChange": 0, "leap_seconds": 18, "satellites_count": 27, "survey_in_position_error": 8 } }
```
2. ptpcheck shows:
```
Oscillator:
model: sa5x
fine_ctrl: -625
coarse_ctrl: 10000
lock: true
temperature: 46.94C
GNSS:
fix: Time (3)
fixOk: true …
```
> Gnss survey

- calnex/api/api.go
- calnex/api/api_test.go
- calnex/cmd/cmd.go
- calnex/cmd/export.go
- calnex/export/export.go
- calnex/export/export_test.go
If we simply keep reset=false by default we will no be able to run 2 exports in parallel (for debug purposes for example) because we will lose the data in between.
Make reset=true by default (every time export all data) and make reset=false configurable with a bit saner name (`allData`). We will make sure export scripts run with `reset=false` and by default human will run with `reset=true` not to lose data.
```
$ calnex -- export --source calnex01.example.com --channel d
```
Dumps all the data
```
$ calnex -- export --source calnex01.example.com --channel d --allData=false
```
Only dumps unread data
> [calnex] make reset configurable

- cmd/README.md
As of Go 1.18, `go get` is deprecated for installing executables.
This commit adds `go install github.com/facebook/time/cmd/ntpcheck@latest` to section quick install as install command with Go 1.18.
https://go.dev/doc/go-get-install-deprecation
This pull request changes cmd/README.md only, there are no code changes.
> Update cmd/README with "go install"

- .packit.yaml
We won't be able to support F35 anyway as we rely on Go 1.18, and having signal for older distro versions we no longer provide updates for makes little sense.
Same with rawhide - things can break there, and we don't want this noise here.
Wait for CI to kick in.
> Update packit to only build on latest stable Fedora

- calnex/config/config.go
- calnex/config/config_test.go
Enable a special PPS mode to avoid 1s jumps
```
$ config --target calnex.example.com --apply
INFO[0004] setting tie_mode to TIE + 1 PPS Alignment
INFO[0004] pushing the config
INFO[0026] starting measurement
```
UI accepted the change
Measurements are collected fine
> [calnex] set tie_mode to TIE + 1 PPS Alignment

- .github/workflows/test.yml
We now have fuzzing tests in `ptp/protocol`, let's run them on PRs.
Look at CI for this change.
> Enable fuzzing in ptp/protocol tests on CI

- .github/workflows/test.yml
Seems like adding fuzzing tests broke codecov, this PR should fix it.
Followed https://github.com/codecov/example-go
CI
> Update codecov integration

- ptp/protocol/doc.go
- ptp/protocol/protocol.go
- ptp/protocol/protocol_test.go
- ptp/protocol/tlvs.go
- ptp/protocol/tlvs_test.go
- ptp/protocol/types.go
- ptp/protocol/types_test.go
- ptp/protocol/unicast.go
- ptp/ptp4u/server/subscription.go
- ptp/simpleclient/client_test.go
In the old repo (now archived) we had this issue https://github.com/facebookarchive/ptp/issues/30 saying we don't support path tracing.
This change:
* adds more TLVs (PATH_TRACE and ALTERNATE_TIME_OFFSET_INDICATOR)
* allows Announce msgs to have TLVs (as per standard any packet can have TLVs in the suffix).
* adds `PTPSeconds` type
Closes https://github.com/facebookarchive/ptp/issues/30
unittests
**benchmarks** show that there is no regression
was:
```
abulimov@devvm1655 ~/g/time > go test github.com/facebook/time/ptp/protocol/... -bench=. -benchmem
goarch: amd64
pkg: github.com/facebook/time/ptp/protocol
cpu: Intel Core Processor (Broadwell)
BenchmarkReadSyncDelay-24       66118900                17.17 ns/op            0 B/op          0 allocs/op
BenchmarkWriteSync-24           55006518 …
```
> [ptp/protocol] support more TLVs

- cmd/ntpcheck/checker/checkresult.go
- cmd/ntpcheck/checker/stats.go
- cmd/ntpcheck/checker/stats_test.go
Summary:
Add a metric to report on number of upstream NTP peers
Test Plan:
```
./ntpcheck stats
{"ntp.peer.delay":0,"ntp.peer.poll":128,"ntp.peer.jitter":0,"ntp.peer.offset":0.02109100023517385,"ntp.peer.stratum":2,"ntp.sys.frequency":-2.807772636413574,"ntp.stat.error":false,"ntp.correction":0.000011605097824940458,"ntp.peer.count":19}
```
> [ntpcheck] add peer count metric

- ntp/chrony/packet.go
- ntp/chrony/packet_test.go
This PR adds support for the `activity` command to the chrony package.
[chrony docs](https://chrony.tuxfamily.org/doc/4.2/chronyc.html):
> **activity**
This command reports the number of servers and peers that are online and offline. If the auto_offline option is used in specifying some of the servers or peers, the activity command can be useful for detecting when all of them have entered the offline state after the network link has been disconnected.
We use `tracking` and `activity` commands for [chrony monitoring](https://github.com/netdata/netdata#netdata-is-high-fidelity-infrastructure-monitoring-and-troubleshootingopen-source-free-preconfigured-opinionated-and-always-real-time). I'd like to get this PR merged so we can use this library.
- The changes are pretty straightforward:
- …
> feat(chrony): add activity command

- ptp/ptp4u/server/server.go
- ptp/ptp4u/server/server_test.go
- ptp/ptp4u/server/worker.go
- ptp/ptp4u/server/worker_test.go
Announce messages is a primary mechanism behind the BMCA. We need to send them as soon as possible if something changes.
On the other hand sending them too often can lead to frequent BMCA selection, which sometimes is more damaging than useful.
In any case, sending announce messages on ptp4u SIGHUP will allow us to increase the announce message interval and at the very least greatly reduce traffic.
Manually sending SIGHUP to ptp4u
+ unit tests of course
> [ptp4u] send announce to all clients if config changes

- ptp/ptp4u/server/server.go
FOREIGN_MASTER_THRESHOLD  is in fact 2 https://github.com/richardcochran/linuxptp/blob/ef9ba9489c2f664ea34e5e4dbddbb76cddef5254/foreign.h#L28
So let's send 2 and not 3 which may actually mess with ptp4l state machine.
> [ptp4l] only send 2 extra announce messages

- ptp/ptp4u/server/server.go
- ptp/ptp4u/server/server_test.go
- ptp/ptp4u/server/subscription.go
- ptp/ptp4u/server/subscription_test.go
- ptp/ptp4u/server/worker.go
- ptp/ptp4u/server/worker_test.go
- ptp/ptp4u/stats/json.go
- ptp/ptp4u/stats/json_test.go
- ptp/ptp4u/stats/stats.go
- ptp/ptp4u/stats/stats_test.go
* Introduce reload channel which allows to trigger subscription loop faster than normal interval.
* Use the reload during stop. Modify unittests to verify this.
* Split signaling counters into Grant and Cancel to monitor them separately
> [ptp4u] faster subscription cancellation

- ptp/ptp4u/server/config.go
- ptp/ptp4u/server/server.go
- ptp/ptp4u/server/server_test.go
- ptp/ptp4u/server/subscription.go
- ptp/ptp4u/server/subscription_test.go
- ptp/ptp4u/server/worker.go
- ptp/ptp4u/server/worker_test.go
Currently server directly responds to the signaling messages (grants).
However, we already have powerful mechanism of sending messages (sync/fwup/announce/delayResp) via workers.
This change will leverage workers to send grants, completely removing send logic from the server.
This will unblock cancellation messages being generated within the subscription on cancel.
> [ptp4u] signaling messages done by workers

- ptp/ptp4u/server/worker.go
Greatly reduce number of allocations by using buffers already defined in send workers.
> [ptp4u] reduce heap allocations for signaling grants

- calnex/api/api.go
- calnex/api/api_test.go
- calnex/cert/cert.go
- calnex/cmd/config.go
- calnex/firmware/firmware_test.go
- cmd/ntpcheck/cmd/utils.go
- cmd/ziffy/node/receiver.go
- leapsectz/leapsectz.go
- leapsectz/leapsectz_test.go
- ntp/chrony/helpers.go
- ntp/chrony/packet.go
- ptp/c4u/c4u_test.go
- ptp/c4u/stats/json_test.go
- ptp/protocol/doc.go
- ptp/protocol/management.go
- ptp/protocol/protocol.go
- ptp/protocol/types.go
- ptp/ptp4u/drain/file_test.go
- ptp/ptp4u/server/config_test.go
- ptp/ptp4u/server/server_test.go
- ptp/ptp4u/stats/json_test.go
* Since Go 1.16 `io/ioutil` got deprecated. Replacing it with alternatives.
* Since Go 1.19 `fmt` got stricter on the comments. Running go fmt on 1.19.
> [time] migrate off io/ioutil

- cmd/ptpcheck/cmd/diag.go
- cmd/ptpcheck/cmd/diag_test.go
Wouldn't it be great if we could rely on exit code to see if all is good?
With this change this dream becomes a reality, and ptpcheck will return the number of failed tests via exit code, and 127 if it failed miserably.
unittests
manual run:
```
abulimov@dev0003 ~/g/time > sudo ./ptpcheck diag; echo $?
[ OK ] GM is present
[ OK ] Period since last ingress is 762.556412ms, we expect it to be within 1s
[ OK ] GM offset is 34ns, we expect it to be within 250µs
[ OK ] GM mean path delay is 4.96µs, we expect it to be within 100ms
[ OK ] Sync timeout count is 0, we expect it to be within 100
[ OK ] Announce timeout count is 0, we expect it to be within 100
[ OK ] Sync mismatch count is 0, we expect it to be within 100
[ OK ] FollowUp mismatch count is 0, we expect it to be within 100
0 …
```
> [ptpcheck] update diag to return exit code depending on result

- ptp/ptp4u/server/server.go
- ptp/ptp4u/server/server_test.go
Reverting an extra announce on ptp4u reload.
> [ptp4u] don't send announce on reload

- timestamp/timestamp.go
- timestamp/timestamp_linux.go
Enabling timestamps requires `CAP_NET_ADMIN` capabilities, and we may already have them enabled when configuring socket.
ran ptpcheck trace on MLNX and BCM machines, all works as expected.
if hw ts is not enabled we get correct msg:
```
failed to run ioctl SIOCSHWTSTAMP to set timestamps enabled: EPERM (operation not permitted)
```
if it's not supported, we get correct msg as well:
```
failed to run ioctl SIOCGHWTSTAMP to see what is enabled: ENOTSUP (operation not supported)
```
> [timestamp] check if hw timestamps are enabled before enabling them

- .packit.yaml
Builds will show up under https://copr.fedorainfracloud.org/coprs/g/meta/time/
> Use dedicated copr for packit builds

- phc/offset.go
- phc/phc.go
* ClockAdjtime function, similar to what `unix` package provides
* `IfaceToPHCDevice` function to help with mapping from iface to phc device
* Export `FBToClockID` so people using `ClockAdjtime` have this helper
* `FrequencyPPB` and `FrequencyPPBFromDevice` to simply get frequency from nic/phc
manual runs of tools using this new functions
> [phc] ClockAdjtime and helper to get PHC frequency

- ptp/ptp4u/server/server.go
Avoid returning an error on graceful shutdown.
Before:
```
ptp4u -workers 200 -timestamptype hardware -loglevel warning -dscp 35 -config /etc/ptp4u.yaml
WARN[0023]third-party-source/go/github.com/facebook/time/ptp/ptp4u/server/server.go:462 third-party-source/go/github.com/facebook/time/ptp/ptp4u/server.(*Server).handleSigterm() Shutting down ptp4u                          
WARN[0023]third-party-source/go/github.com/facebook/time/ptp/ptp4u/server/server.go:420 third-party-source/go/github.com/facebook/time/ptp/ptp4u/server.(*Server).Drain() Still waiting for 1 subscriptions on worker 118 to finish... 
FATA[0024]ptp/ptp4u/main.go:142 main.main() Server run failed: one of server routines finished 
```
After:
```
ptp4u -workers 200 -timestamptype hardware -loglevel warning -dscp 35 -config …
```
> [ptp4u] graceful shutdown

- README.md
- cmd/README.md
- cmd/fbclock-bin/Makefile
- cmd/fbclock-bin/fbclock-bin.c
- cmd/fbclock-daemon/main.go
- fbclock/Makefile
- fbclock/daemon/config.go
- fbclock/daemon/daemon.go
- fbclock/daemon/daemon_test.go
- fbclock/daemon/device.go
- fbclock/daemon/json_stats.go
- fbclock/daemon/logging.go
- fbclock/daemon/logging_test.go
- fbclock/daemon/math.go
- fbclock/daemon/math_test.go
- fbclock/daemon/state.go
- fbclock/daemon/stats.go
- fbclock/fbclock.c
- fbclock/fbclock.go
- fbclock/fbclock.h
- fbclock/missing.h
- fbclock/shmem.go
- fbclock/shmem_test.go
- fbclock/stats.go
- fbclock/stats_test.go
- fbclock/test/test.cpp
Open-source our implementation of TrueTime service.
New stuff:
* `fbclock` - C lib and CGO wrapper for it
* `fbclock/daemon` - stateful part of fbclock
* `cmd/fbclock-daemon` - daemon for stateful part
* `cmd/fbclock-bin` - C tool to use fbclock API
Proper docs for fbclock will follow in a separate PR, this is big enough already.
tests pass, build works:
```
go build github.com/facebook/time/cmd/fbclock-daemon
```
```
> cd cmd/fbclock-bin
> make
```
```
> cd fbclock
> make test
[       OK ] fbclock_test.test_fbclock_calculate_time (0 ms)
[----------] 4 tests from fbclock_test (46 ms total)
[----------] Global test environment tear-down
[==========] 4 tests from 1 test case ran. (46 ms total)
[  PASSED  ] 4 tests.
```
> open-source fbclock

- cmd/fbclock-daemon/main.go
- fbclock/daemon/config.go
- fbclock/daemon/daemon.go
- fbclock/daemon/device.go
- phc/offset.go
- phc/offset_test.go
- phc/phc.go
- phc/phc_test.go
On multi-NIC devices we can't just assume that `/dev/ptp0` corresponds to `eth0`. Stop making assumptions and accept iface to use, as we still need to know it for linearizability tests.
Local run, making sure correct PHC is used for operations.
For example, managed device setup:
```
> ptpcheck map
No PHC support for lo
/dev/ptp0 -> eth8
/dev/ptp1 -> eth5
/dev/ptp2 -> eth0
/dev/ptp3 -> eth11
/dev/ptp4 -> eth4
/dev/ptp5 -> eth1
/dev/ptp6 -> eth6
/dev/ptp7 -> eth7
/dev/ptp8 -> eth2
/dev/ptp9 -> eth9
/dev/ptp10 -> eth10
/dev/ptp11 -> eth3
```
notice that `/dev/ptp2 -> eth0` line.
Now let's make sure we set up the device correctly:
```
> ls -lhi /dev/ptp2
698 crw-r--r-- 2 root root 249, 2 Sep 26 21:26 /dev/ptp2
> ls -lhi /dev/fbclock/ptp
698 crw-r--r-- 2 root root 249, 2 Sep 26 21:26 …
```
> [fbclock] use network interface instead of phc device path

- cmd/ptpcheck/cmd/phcdiff.go
- cmd/ptpcheck/cmd/phcdiff_test.go
`ptpcheck phcdiff` subcommand to print difference between two PHC devices
```
> ./ptpcheck phcdiff --json
{"ptp.phc.offset_ns":-22,"ptp.phc.1.delay_ns":358,"ptp.phc.2.delay_ns":2581}
> ./ptpcheck phcdiff
PHC offset: -10ns
Delay for PHC1: 357ns
Delay for PHC2: 2.592µs
```
> [ptpcheck] add phcdiff subcommand

- cmd/ptp4u/main.go
- ptp/ptp4u/server/config.go
- ptp/ptp4u/server/subscription.go
- ptp/ptp4u/server/subscription_test.go
Added a default DomainNumber for subscriptions. 
Currently it is It's hardcoded to 0 in
https://github.com/facebook/time/blob/main/ptp/ptp4u/server/subscription.go#L205
Unit test and internal manual test on time servers
> ptp/ptp4u: add default DomainNumber support #219

- .packit.yaml
Temporarily disable s390 builds because of missing dependencies:
```
Problem: package golang-github-kit-devel-0.11.0-4.fc37~bootstrap.noarch requires golang(google.golang.org/grpc), but none of the providers can be installed
- package golang-github-kit-devel-0.11.0-4.fc37~bootstrap.noarch requires golang(google.golang.org/grpc/codes), but none of the providers can be installed
- package golang-github-kit-devel-0.11.0-4.fc37~bootstrap.noarch requires golang(google.golang.org/grpc/status), but none of the providers can be installed
- package golang-github-kit-devel-0.11.0-4.fc37~bootstrap.noarch requires golang(google.golang.org/grpc/metadata), but none of the providers can be installed
- package golang-google-grpc-devel-1.48.0-7.fc37.noarch requires …
```
> [ci] temporarily disable fedora s390

- ptp/protocol/types.go
`file` does not like `ptp/protocol/types.go`:
```
$ file ptp/protocol/types.go
ptp/protocol/types.go: data
```
```sh
$ file ptp/protocol/types.go
ptp/protocol/types.go: ASCII text
```
> [chore] replace control character with space

- cmd/ptpcheck/cmd/diag.go
- cmd/ptpcheck/cmd/diag_test.go
Negative path delay is a symptom of a serious problem, make sure ptpcheck clearly shows it.
unittests
> [ptpcheck] diag: fail on negative path delay

- ptp/ptp4u/server/worker.go
TX timestamp failures not recovering. It's better to crash than keep operating without a timestamp
> [ptp4u] crash on TX timestamp unavailability
