README.md
ntpcheck/checker/checkresult.go
ntpcheck/checker/checkresult_test.go
ntpcheck/checker/chrony.go
ntpcheck/checker/chrony_test.go
ntpcheck/checker/doc.go
ntpcheck/checker/ntpd.go
ntpcheck/checker/ntpd_test.go
ntpcheck/checker/peer.go
ntpcheck/checker/peer_test.go
ntpcheck/checker/serverstats_test.go
ntpcheck/checker/system.go
ntpcheck/checker/system_test.go
protocol/chrony/README.md
protocol/chrony/client.go
protocol/chrony/client_test.go
protocol/chrony/doc.go
protocol/chrony/packet.go
protocol/control/README.md
protocol/control/client.go
protocol/control/client_test.go
protocol/control/doc.go
protocol/control/packet.go
protocol/control/packet_test.go

* added tons of unittests, especially for ntpcheck
* made ntp control library more useful by adding helper functions to manipulate composite bit words
* made more structures public in chrony library, as keeping them private made little sense
* improved docs and added GoDoc badges
This change doesn't alter any logic, mostly adds unittests, and tests are passing.

Add more tests, better docs, refactoring

---

protocol/ntp/ntp.go
protocol/ntp/ntp_test.go
protocol/ntp/packet.go
responder/announce/noop.go
responder/checker/simplechecker.go
responder/server/config.go
responder/server/ip.go
responder/server/server.go
responder/stats/json.go

Improve godoc

---

responder/server/interfaces.go
responder/server/server.go
responder/stats/json.go
responder/stats/json_test.go

Follow up of #29:
* Add suggested error message
* Add read error counter

stats: add read error counter

---

protocol/ntp/ntp.go
protocol/ntp/packet.go

* change `connFd` so that it doesn't create a dup fd
* replace `syscall.Recvmsg` with `ReadMsgUDP`
Fixes #31

fix read errors

---

responder/main.go
responder/server/ip.go
responder/server/server.go

We were removing IPs before actually waiting for drain
Deployed on 1 test job

Drain first, remove IPs later

---

responder/main.go

No need in this loop, select is blocking
```
sudo go run github.com/facebookincubator/ntp/responder --ip 1.2.3.4 --ip 2.3.4.5 -interface lo0
WARN[0000] Creating 800 goroutine workers
WARN[0000] Starting 2 listener(s)
INFO[0000] Starting listener on 1.2.3.4:123
INFO[0000] Starting listener on 2.3.4.5:123
INFO[0000] Adding 1.2.3.4 to lo0
INFO[0000] Adding 2.3.4.5 to lo0
```

Remove useless loop

---

protocol/ntpshm/ntpshm.go

Add SHMTime to simplify read
Just a wrapper around tested functions

SHMTime helper

---

responder/stats/json_test.go

[responder] fix test

---

go.sum
ntpcheck/checker/checkresult_test.go
ntpcheck/checker/chrony_test.go
ntpcheck/checker/ntpd_test.go
ntpcheck/checker/peer_test.go
ntpcheck/checker/serverstats_test.go
ntpcheck/checker/stats_test.go
ntpcheck/checker/system_test.go
protocol/chrony/client_test.go
protocol/chrony/helpers_test.go
protocol/control/client_test.go
protocol/control/packet_test.go
protocol/ntp/ntp_darwin_test.go
protocol/ntp/ntp_freebsd_test.go
protocol/ntp/ntp_linux_test.go
protocol/ntp/ntp_test.go
protocol/ntpshm/ntpshm_test.go
responder/checker/simplechecker_test.go
responder/server/config_test.go
responder/server/ip_darwin_test.go
responder/server/ip_freebsd_test.go
responder/server/ip_linux_test.go
responder/server/ip_test.go
responder/server/server_test.go
responder/stats/json_test.go

Couple of seds to:
* Remove usage of `assert` in favour of `require`
* `'s/require.Nil(t, err)/require.NoError(t, err)/g'`
* `'s/require.NotNil(t, err)/require.Error(t, err)/g'`
Unittests

Unify test style

---

ntpcheck/checker/chrony.go
ntpcheck/checker/runner.go

Abstract chrony unix socket connection to simplify `RunCheck` function.

[chrony] abstract unix socket connection

---

ntpcheck/checker/chrony_test.go
ntpcheck/checker/ntpd.go
ntpcheck/checker/ntpd_test.go

* Remove underscore from tests
* Remove confusing message from logs

[ntpcheck] NITs

---

calnex/README.md
calnex/api/api.go
calnex/api/api_test.go
calnex/api/ini.go
calnex/api/proto.go
calnex/api/proto_test.go
calnex/cmd/clear.go
calnex/cmd/cmd.go
calnex/cmd/config.go
calnex/cmd/export.go
calnex/cmd/firmware.go
calnex/cmd/reboot.go
calnex/cmd/report.go
calnex/config/config.go
calnex/config/config_test.go
calnex/export/data.go
calnex/export/data_test.go
calnex/export/export.go
calnex/export/export_test.go
calnex/firmware/firmware.go
calnex/firmware/firmware_test.go
calnex/firmware/ossfirmware.go
calnex/firmware/ossfirmware_test.go
calnex/main.go
calnex/testdata/config.json
calnex/testdata/sentinel_fw_v3.0.tar
go.mod
go.sum

Open source the calnex tool
```
./calnex firmware --target calnex01.example.com --file ~/go/github.com/facebook/time/calnex/testdata/sentinel_fw_v3.0.tar --proto http
INFO[0000] calnex01.example.com is running 2.1, latest is 3.0.0. Needs an update
INFO[0000] dry run. Exiting
```

Open source Calnex tool

---

ptp/oscillatord/monitoring_test.go

Add tests to improve coverage
unittests obviously :)

Improve oscillatord test coverage

---

calnex/api/api.go
calnex/api/api_test.go
calnex/cmd/config.go
calnex/cmd/config_test.go
calnex/testdata/config.json

Simplify JSON config file parsing by directly unmarshaling into the struct
unittests

Simplify JSON unmarshal for the Calnex config

---

calnex/config/config.go
calnex/config/config_test.go

Explicitly set json names for lowercase export of the public structs

[Calnex] explicitly set json names

---

calnex/api/api.go
cmd/ntpcheck/checker/checkresult.go
cmd/ptpcheck/cmd/diag.go
leaphash/leaphash.go
ntp/chrony/client_test.go
ntp/control/client_test.go
ntp/control/packet.go
ntp/responder/server/config.go
ptp/protocol/types.go
ptp/ptp4u/README.md
ptp/simpleclient/client.go
timestamp/timestamp.go

Simply correct spelling mistakes accumulated over the years.
```
go run github.com/client9/misspell/cmd/misspell -w ./*
```

Correct spelling errors

---

ntp/responder/checker/simplechecker.go
ntp/responder/server/server_test.go

Write basic tests to improve overall coverage
```
$ go test -race github.com/facebook/time/ntp/...
```

[ntp/responder] improve test coverage

---

cmd/pshark/main.go
ptp/protocol/protocol.go
ptp/ptp4u/server/server_test.go
ptp/ptp4u/server/worker_test.go

More unit tests including launching real workers to see if they panic for example.
Unit tests obviously :P

[ptp4u] improve test coverage

---

.circleci/linters.sh

Add a spelling linter
```
$ go run github.com/client9/misspell/cmd/misspell -error ./*
./typos.txt:4:3: "langauge" is a misspelling of "language"
exit status 2
$ echo $?
1
```

[linter] check spelling

---

calnex/api/api.go
calnex/api/api_test.go
calnex/cmd/export.go
calnex/cmd/report.go
calnex/config/config.go
calnex/config/config_test.go
calnex/export/export_test.go
calnex/firmware/firmware_test.go

Implement support of API v2.0 (r17) which allows to config/export virtual channels VP1-30
Internal testing. Metrics collected.

[calnex] implement API v2.0 support

---

ptp/ptp4u/server/server.go
ptp/ptp4u/server/server_test.go
ptp/ptp4u/stats/json.go
ptp/ptp4u/stats/json_test.go
ptp/ptp4u/stats/stats.go
ptp/ptp4u/stats/stats_test.go

[ptp4u] drain stats

---

cmd/ptp4u/main.go
ptp/ptp4u/drain/check.go
ptp/ptp4u/drain/file.go
ptp/ptp4u/drain/file_test.go
ptp/ptp4u/server/config.go
ptp/ptp4u/server/server.go

Without file:
```
curl localhost:8888
{"drain":0,"utcoffset":37}
```
With file:
```
curl localhost:8888
{"drain":1,"utcoffset":37}
```

[ptp4u] drain interface

---

ptp/ptp4u/drain/check.go
ptp/ptp4u/drain/file.go
ptp/ptp4u/drain/file_test.go

[drain] add license header

---

ptp/ptp4u/drain/file.go

[drain] fix spell

---

calnex/api/api.go
calnex/api/api_test.go

Add API call to get GNSS status.

[calnex] gnss api

---

calnex/api/api.go

[calnex] api: fix lint warning

---

README.md

[ci] use github actions #3

---

.github/workflows/lint.yml
cmd/ntpcheck/cmd/utils_notdarwin.go

[ci] use github actions #6

---

.circleci/config.json

Follow up from #129.
```
$ go run github.com/u-root/u-root/tools/checklicenses -c .circleci/config.json
$ echo $?
0
```

[ci] use github actions #7

---

.circleci/linters.sh

[ci] use github actions #8

---

cmd/ptp4u/main.go
ptp/ptp4u/server/config.go
ptp/ptp4u/server/config_test.go
ptp/ptp4u/server/server.go

* Make sure raw values from DynamicConfig are used.
* Leap info should be only read from the cfg file (we will generate it later).
Metrics, drain works fine:

[ptp4u] always use dynamic config options directly

---

cmd/ptp4u/main.go
ptp/ptp4u/server/config.go
ptp/ptp4u/server/config_test.go

Export pid file so its easier to interact with the service.
```
$ cat /var/run/ptp4u.pid
2327891
$ systemctl stop ptp4u
$ cat /var/run/ptp4u.pid
cat: /var/run/ptp4u.pid: No such file or directory
```

[ptp4u] export pid file

---

cmd/c4u/main.go
ptp/c4u/c4u.go
ptp/c4u/c4u_test.go
ptp/c4u/clock/clock.go
ptp/c4u/clock/clock_test.go
ptp/ptp4u/server/config_test.go

* Rename TAU to Samples as better representing name. Bump to 10 minutes by default.
* Add run once option.
* Introduce Interval option.
* Change cfg generation logic to avoid stale data if clock sources irresponsive down.
* Add unit tests.
```
$ ./c4u -once
INFO[0000] Current: &{ClockAccuracy:35 ClockClass:6 DrainInterval:30s MaxSubDuration:1h0m0s MetricInterval:1m0s MinSubInterval:1s UTCOffset:37s}
INFO[0000] Pending: &{ClockAccuracy:33 ClockClass:6 DrainInterval:30s MaxSubDuration:1h0m0s MetricInterval:1m0s MinSubInterval:1s UTCOffset:37s}
```
```
$ ./c4u
INFO[0000] Current: &{ClockAccuracy:35 ClockClass:6 DrainInterval:30s MaxSubDuration:1h0m0s MetricInterval:1m0s MinSubInterval:1s UTCOffset:37s}
INFO[0000] Pending: &{ClockAccuracy:33 ClockClass:6 DrainInterval:30s …
```

[c4u] improve source edge cases handling

---

ptp/ptp4u/server/server.go
ptp/ptp4u/stats/json.go
ptp/ptp4u/stats/json_test.go
ptp/ptp4u/stats/stats.go
ptp/ptp4u/stats/stats_test.go

Report clock class and clock accuracy

[ptp4u] add clock stats

---

calnex/cmd/export.go
calnex/export/export.go
calnex/export/export_test.go

Allow other actions to be taken with an entry.

[calnex][export] handler function

---

cmd/c4u/main.go
ptp/c4u/c4u.go
ptp/c4u/c4u_test.go
ptp/c4u/clock/clock.go
ptp/c4u/clock/clock_test.go
ptp/c4u/clock/math.go
ptp/c4u/clock/math_test.go

* Implement custom formula expression for clockClass
* Implement p99 support in formula 
* More tests
Tests

[c4u] implement p99 for clock class calculations

---

cmd/c4u/main.go

Improves long term stability.
The reaction time with normal distribution will move from 6 seconds to ~36 seconds.

[c4u] increase ring buffer to 3600

---

ptp/c4u/c4u.go
ptp/c4u/clock/oscillatord.go
ptp/c4u/clock/oscillatord_test.go

Just a rename, noop
unittests obvs

[c4u] better function name

---

.github/workflows/test.yml

Enable fuzzing in ntp tests on CI

---

cmd/ntpcheck/checker/chrony.go
cmd/ntpcheck/checker/chrony_test.go
cmd/ntpcheck/checker/peerstats.go
cmd/ntpcheck/checker/peerstats_test.go
cmd/ntpcheck/checker/runner.go
cmd/ntpcheck/checker/runner_test.go
cmd/ntpcheck/checker/stats.go

Add more ntpcheck tests

---

cmd/ptpcheck/checker/checker.go
cmd/ptpcheck/checker/checker_test.go

More tests == good
```
> go test github.com/facebook/time/cmd/ptpcheck/... -cover 
?       github.com/facebook/time/cmd/ptpcheck   [no test files]
ok      github.com/facebook/time/cmd/ptpcheck/checker   0.006s  coverage: 72.5% of statements
ok      github.com/facebook/time/cmd/ptpcheck/cmd       0.006s  coverage: 18.1% of statements
```

Add more ptpcheck tests

---

ptp/ptp4u/server/server_test.go

No code change.
Improve the test to make 100% sure we never send sync packets on reload.

[ptp4u] improve TestHandleSighup

---

ptp/ptp4u/server/server.go

Apparently ptp4l is waiting for exactly 3 announce messages before doing anything:
https://sourceforge.net/p/linuxptp/mailman/message/37685839/
1 it ignores 
https://github.com/richardcochran/linuxptp/blob/33ac7d25cd9212e79be6f7023ba18cfa5020e35b/port.c#L408
And 2 we just wait
https://github.com/richardcochran/linuxptp/blob/33ac7d25cd9212e79be6f7023ba18cfa5020e35b/port.c#L2546
This hack will ensure we send all 2+1 right away so we don't have to wait for a long time after restart.
```
$ systemctl restart ptp4l ; tcpdump -pi any host srv
...
10:55:32.403753 IP6 srv.37169 > cli.ptp-general: UDP, length 66
10:55:32.403809 IP6 srv.37169 > cli.ptp-general: UDP, length 66
10:55:32.403809 IP6 srv.37169 > cli.ptp-general: UDP, length 66
...
```
```
$ journalctl -u ptp4l -f
Jul 25 10:55:32 cli …
```

[ptp4u] extra announce messages for faster ptp4l restart

---

ptp/ptp4u/server/server_test.go
ptp/ptp4u/server/subscription.go

Additional announces do more harm than good at this point.
Saving for a better day
Internal tests

[ptp4l] don't send extra announces

---

ptp/ptp4u/server/subscription.go
ptp/ptp4u/server/subscription_test.go

Further simplify "reload" logic only keeping it for "stop"
This allows great simplification and smaller chance of a race condition.
Deployed to prod

[ptp4u] simplify stop logic

---

ptp/protocol/types.go

Add another class defined in RFC which we missed
https://datatracker.ietf.org/doc/html/rfc8173#section-7.6.2.4

[ptp] add clockclass14

---

ptp/ptp4u/server/server.go

Typically, `WaitGroup` is [used](https://gobyexample.com/waitgroups) to track all go routines and wait for the last one to exit.
We sort of abused this and only added waiting for any Go routine to exit, which in our case would signal a failure and log the error.
Since the original implementation, we added `handleSigterm()` logic which terminates its routine when the `SIGTERM` is received. This is not a failure scenario, but we piggybacked on the `wg.Wait()` anyway.
Because of that every, time we shut down gracefully we had error returned. This has been worked around in https://github.com/facebook/time/pull/214 where we still exit `wg.Wait()` but then check "why" using a bool variable.
This diff replaces the bool variable with a channel (which is a canonical way to handle signals) and the …

[ptp] implement graceful shutdown with channels

---

fbclock/missing.h

[fbclock] add missing copyright header

---

cmd/ntpcheck/checker/chrony.go
cmd/ntpcheck/checker/serverstats.go
ntp/chrony/packet.go

Similar to https://github.com/facebook/time/pull/55
Support the reply introduced in https://github.com/mlichvar/chrony/commit/1fb60f8db80ded51691786397c72de755d22f977

[ntpcheck] support serverstats with chrony 4.2

---

ptp/ptp4u/server/config.go

ptp: sort config properties

---

ptp/c4u/clock/clock.go

Print actual arrays to simplify debugging
```
c4u[3642166]: time="2022-12-19T05:37:12-08:00" level=debug msg="phcOffsets = [7 11 6 21 29 34 13 1 11 27 30 -5 32 13 17 29 24 8 6 8 -3 -6 0 5 29 8 28 30 9 2 -1 20 12 23 29 5 12 28 4 10 24 40 25 8 20 37 -7 21 13 17 18 8 -1 46 31 18 15 -6 1 18 8 16 2 37 17 11 13 26 25 16 3 18 -7 30 -3 12 -1 9 43 2 20 -8 26 18 -6 14 15 0 -3 11 -3 9 -1 -1 28 30 0 47 11 41 27 12 -5 4 26 0 39 7 29 16 14 -3 38 27 10 10 14 54 21 40 -39 20 21 -18 27 31 9 18 27 13 18 45 48 13 21 7 34 17 15 24 13 18 25 45 27 11 23 19 52 0 42 5 10 1 14 26 11 39 24 32 10 21 12 15 -1 10 26 13 51 2 -7 19 -5 20 8 18 0 34 27 38 34 20 5 12 25 -2 28 22 42 16 7 16 7 4 20 13 2 17 26 13 3 24 24 22 35 19 25 14 -13 20 25 24 36 21 40 20 31 11 5 8 -3 -31 12 12 41 9 -6 48 34 19 16 24 7 8 -2 48 -11 22 6 …
```

[c4u] print offsets in debug mode

---

.packit.yaml

Update this to the latest syntax and build for all supported releases.
Closes: #238

Update packit config
